#!/usr/bin/env python
# -*-python-*-

import sys
import os
import logging

import mapzen.whosonfirst.sources

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')

    options, args = opt_parser.parse_args()

    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    for src in args:

        valid = mapzen.whosonfirst.sources.is_valid_source(src)
        logging.info("%s is valid: %s" % (src, valid))

        if not valid:
            continue

        source = None

        if not source:
            source = mapzen.whosonfirst.sources.get_source_by_name(src)
            logging.info("get %s by name %s" % (src, source))

        if not source:
            source = mapzen.whosonfirst.sources.get_source_by_prefix(src)
            logging.info("get %s by prefix %s" % (src, source))

        if not source:
            source = mapzen.whosonfirst.sources.get_source_by_id(src)
            logging.info("get %s by id %s" % (src, source))
